import { ref, computed } from "vue";
import { defineStore } from "pinia";

export const useDialogStore = defineStore("dialog", () => {
  const dialogs = [
    {
      id: 1,
      theme: "Salomlashuv",
      theme_ru: "Приветствие",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет!",
          uz: "Salom!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Как твои дела?",
          uz: "Salom! Ishlaring qalay?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Всё отлично, спасибо. Как у тебя?",
          uz: "Hammasi yaxshi! Senda qanday?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Тоже всё хорошо.",
          uz: "Hammasi joyida.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как прошел твой день?",
          uz: "Kuning qanday o'tdi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "День был насыщенный, но удачный. А у тебя как прошел?",
          uz: "Kun ishlarga(tashvishlarga) to’la, lekin omadli bo'ldi. Senikichi qanday o'tdi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Тоже был занят, но в целом неплохо.",
          uz: "Men ham ish bilan band edim, lekin umuman olganda, yomon o’tmadi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Что нового у тебя?",
          uz: "Senda nima yangiliklar?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ничего особенного, просто работа и обычные дела. А у тебя?",
          uz: "Hech qanday ahamiyatli narsalar yo'q, faqat ish va odatiuy narsalar. Sendachi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Так же, ничего особенного.",
          uz: "Xuddi shunday, hech qanday ahamiyatli narsalar yo'q.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Какие планы на выходные?",
          uz: "Dam olish kunlariga qanday rejalaring bor?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Пока не решил, возможно просто отдохну дома. А у тебя?",
          uz: "Hali bir qarorga kelganim yo'q, balki uyda dam olaman. Sendachi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Думаю с друзьями пойти в кино. Пошли с нами!",
          uz: "Do'stlarim bilan kinoga borishni o'ylayapman. Biz bilan bor!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я подумаю, и отвечу в пятницу. Хорошо?",
          uz: "O'ylab ko'raman va juma kuni javobini beraman. Maylimi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Хорошо, договорились!",
          uz: "Yahshi, kelishdik!",
        },
      ],
    },

    {
      id: 2,
      theme: "Tanishuv. Tarjimai hol",
      theme_ru: "Знакомство. Автобиография",
      dialog: [
        {
          gender: "male",
          person: 1,
          ru: "Привет! Как тебя зовут?",
          uz: "Salom! Isming nima?",
        },
        {
          gender: "male",
          person: 2,
          ru: "Привет! Меня зовут Тимур. А тебя? ",
          uz: "Salom! Mening ismim Timur. Senichi?",
        },
        {
          gender: "male",
          person: 1,
          ru: "Меня зовут Максим. Рад знакомству. Ты откуда?",
          uz: "Mening ismim Maks. Sen bilan tanishganimdan xursandman. Qayerdansan? ",
        },
        {
          gender: "male",
          person: 2,
          ru: "Я из Москвы. А ты?",
          uz: "Men Moskvadanman. Senchi?",
        },
        {
          gender: "male",
          person: 1,
          ru: "Я тоже из Москвы. Чем занимаешься?",
          uz: "Men ham Moskvadanman. Nima ish bilan shug’ullanasan?",
        },
        {
          gender: "male",
          person: 2,
          ru: "Я студент. А ты?",
          uz: "Men talabaman. Senchi?",
        },
        {
          gender: "male",
          person: 1,
          ru: "Я тожу  студент, учусь на факультете экономики. Где ты учишься?",
          uz: "Men ham talabaman, iqtisod fakultetida o‘qiyman. Sen qayerda o `qiysan?",
        },
        {
          gender: "male",
          person: 2,
          ru: "А я учусь на факультете журналистики. Какие у тебя хобби? ",
          uz: "Men esa jurnalistika fakultetida o’qiyman. Sevimli mashg'ulotlaring nima?",
        },
        {
          gender: "male",
          person: 1,
          ru: "Я люблю путешествовать и читать книги. А у тебя есть какие-то увлечения?",
          uz: "Men sayohat qilishni va kitob o'qishni yaxshi ko'raman. Sening ham qandaydir  sevimli mashg'ulotlaringiz bormi?",
        },
        {
          gender: "male",
          person: 2,
          ru: "У меня есть несколько хобби: играю на гитаре, играю футбол и смотрю - сериалы. Сколько тебе лет?",
          uz: "Bir nechta sevimli mashg'ulotlarim bor: gitara chalaman, futbol o'ynayman va seriallarni tomosha qilaman. Yoshing nechida?",
        },
        {
          gender: "male",
          person: 1,
          ru: "Мне 21 год. А тебе?",
          uz: "Men 21 yoshdaman. Senchi?",
        },
        {
          gender: "male",
          person: 2,
          ru: "Мне 23 года.",
          uz: "Men 23 yoshdaman.",
        },
        {
          gender: "male",
          person: 1,
          ru: "Очень приятно познакомиться, Максим.",
          uz: "Sen bilan tanishganimdan juda xursandman, Maksim.",
        },
        {
          gender: "male",
          person: 2,
          ru: "Тоже рад знакомству, Тимур. Будем держать связь!",
          uz: "Men  ham tanishganimdan xursandman, Timur. Aloqada bo'lib turaylik!",
        },
      ],
    },

    {
      id: 3,
      theme: "O‘qish",
      theme_ru: "Учёба",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Как проходит учеба?",
          uz: "Salom! O'qishlaring qanday ketyapti?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Неплохо, спасибо. А у тебя?",
          uz: "Salom! Rahmat, yomon emas. Sendachi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Тоже неплохо, хотя иногда бывает тяжело сдавать экзамены.",
          uz: "Menda ham yomon emas, ba'zida imtihonlarni topshirish qiyin  bo’lsa ham.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Понимаю. У меня тоже много учебы, особенно на факультете экономики.",
          uz: "Tushunaman. Mening  ham mashg’ulotlarim ko’p, ayniqsa iqtisod fakultetida.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ты изучаешь какой-нибудь иностранный язык?",
          uz: "Sen biron bir chet tilini o'rganyapsanmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я изучаю английский. А ты?",
          uz: "Men ingliz tilini o'rganayapman. Senchi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "И я. Мне нравится его учить. А какие у тебя любимые предметы?",
          uz: "Men ham. Uni o’rganish menga yoqadi.  Yaxshi ko’rgan fanlaring qanaqa?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Мне нравится экономика.",
          uz: "Menga iqtisod yoqadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как ты обычно готовишься к экзаменам?",
          uz: "Imtihonlarga odatda qanday tayyorlanasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я делаю конспекты и повторяю материал по несколько раз. А ты?",
          uz: "Men konspekt qilaman va materialni bir necha marta takrorlayman. Senchi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я читаю дополнительные материалы.",
          uz: "Men qo'shimcha materiallarni o'qiyman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Ты ходишь на все лекции?",
          uz: "Sen hamma ma'ruzalarga borasanmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Нет, но стараюсь не пропускать.",
          uz: "Yo'q, lekin qoldirmaslikka harakat qilaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я думаю, что лекции могут помочь лучше понять предмет.",
          uz: "Men o‘ylaymanki, ma’ruzalar mavzuni yaxshiroq tushunishga yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это точно!",
          uz: "Bu aniq!",
        },
      ],
    },

    {
      id: 4,
      theme: "Ish. Kasb",
      theme_ru: "Работа. Профессия",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Как у тебя дела на работе?",
          uz: "Salom! Ishxonada ishlaring qanday?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Спасибо, все хорошо. Недавно получил повышение.",
          uz: "Salom! Rahmat, hammasi yaxshi. Yaqinda yuqori lavozimga ko’tarildim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Поздравляю! Какая у тебя профессия?",
          uz: "Tabriklayman! Kasbing  nima?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я работаю программистом, занимаюсь разработкой программного обеспечения. А ты?",
          uz: "Men dasturchi bo'lib ishlayman, dasturiy ta'minot ishlab chiqarish bilan shug’ullanaman. Senchi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я работаю в области маркетинга, занимаюсь продвижением продуктов и услуг.",
          uz: "Men marketing sohasida, mahsulot va xizmatlarni ilgari surish bilan shug’ullanaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "У нас с тобой разные профессии, но обе востребованные.",
          uz: "Bizning  kasblarimiz har xil, lekin ikkalamiz ham talabgormiz.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, каждая профессия имеет свои особенности.",
          uz: "Ha, har bir kasbning o‘ziga xos tomonlari bor.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Как ты думаешь, что важнее - любить свою работу или получать высокую зарплату?",
          uz: "Seningcha, nima muhimroq:  o’z ishini sevmoqmi yoki yuqori maosh olishmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я считаю, что важно сочетать и то, и другое.",
          uz: "Menimcha, ikkalasini ham birlashtirish muhim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это правда, любовь к работе дает мотивацию, а высокая зарплата приятные бонусы.",
          uz: "To'g'ri, ishga bo'lgan muhabbat motivatsiyaini, yuqori maosh esa yoqimli bonuslarni beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Но для меня важнее быть увлеченным своей профессией.",
          uz: "Lekin men uchun o'z kasbimga bo’lgan qiziqish muhimroq turadi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "И для меня! Я мечтаю стать руководителем. Но для начала нужно еще много учиться и накапливать опыт.",
          uz: "Men uchun ham! Men rahbar bo'lishni orzu qilaman. Lekin boshlanishda ko'p narsalarni o'rganish va tajriba to’plash kerak.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, конечно! Важно верить в себя и двигаться к поставленным целям.",
          uz: "Ha albatta! Muhimi o'ziga ishonish va maqsad sari intilish.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Удачи в реализации своих планов!",
          uz: "Rejalaringni amalga oshirishda omad tilayman!",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо! И тебе желаю успехов в карьере.",
          uz: "Rahmat! Senga ham yuqori martabalarga erishishda  muvaffaqiyatlar tilayman.",
        },
      ],
    },

    {
      id: 5,
      theme: "Mening oilam va oilaviy munosabatlar” mavzusi",
      theme_ru: "Моя семья и родственные отношения",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Расскажи мне о своей семье.",
          uz: "Salom! Menga oilang haqida gapirib ber.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! В моей семье четверо человек - я, мои родители и младший брат. А у тебя?",
          uz: "Salom! Mening oilamda to'rt kishi bor - men, ota-onam va ukam. Sendachi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "У меня тоже есть младший брат, он еще учится в школе.",
          uz: "Mening ham ukam bor, u hali maktabda o’qiydi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Мой тоже. Мы очень близки и поддерживаем друг друга.",
          uz: "Meniki ham. Biz juda yaqinmiz va bir-birimizni qo'llab-quvvatlaymiz.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Мы тоже близки, хотя иногда ссоримся.",
          uz: "Biz ham inoqmiz. ba'zida bahslashib tursak ham.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А какие у тебя отношения с родителями?",
          uz: "Ota-onang bilan munosabatlaring qanday?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Мы очень близки и поддерживаем друг друга.",
          uz: "Biz juda yaqinmiz va bir-birimizni qo'llab-quvvatlaymiz.",
        },
        {
          gender: "male",
          person: "2",
          ru: "У меня тоже очень близкие отношения с родителями. Мы часто общаемся, делимся радостями и заботимся друг о друге.",
          uz: "Men ham ota-onam bilan  juda yaqin munosabatdaman. Biz tez-tez muloqot qilamiz, quvonchlarimizni baham ko'ramiz va bir-birimizga g'amxo'rlik qilamiz.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как ты проводишь время со своей семьей?",
          uz: "Oilang bilan vaqtni qanday  o'tkazasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Мы часто собираемся вместе на выходных, готовим вкусные ужины или играем в настольные игры.",
          uz: "Dam olish kunlari tez-tez birga yig’ilamiz, mazali kechki ovqat pishiramiz yoki stol o'yinlarini o'ynaymiz.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это всегда приятно проводить время в кругу близких.",
          uz: "Yaqinlaring bilan vaqt o'tkazish har doim yoqimli.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Ты живете вместе с родителями?",
          uz: "Ota-onang bilan birga yashaysanmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, но у папы и мамы не так много свободного времени, чтобы собираться вместе. Они работают врачами.",
          uz: "Ha, lekin onam va dadamning birga yig’ilishimiz uchun vaqtlari unchalik ko’p emas. Ular shifokor bo'lib ishlashadi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Понимаю! У них такая важная работа.",
          uz: "Tushunarli! Ularning shunday muhim ishlari bor.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, я очень горжусь моими родителями и хочу быть похожим на них.",
          uz: "Ha, men ota-onam bilan juda faxrlanaman va ularga o’xshashni xohlayman.",
        },
      ],
    },

    {
      id: 6,
      theme: "Mening kunim. Kun tartibi",
      theme_ru: "Мой день. Распорядок дня",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Как проходит твой обычный день?",
          uz: "Salom! Sening odatiy kuning qanday o'tadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Я стараюсь придерживаться распорядка. Начинаю день с того, что встаю в 7 утра.",
          uz: "Salom! Men kun tartibiga rioya qilishga harakat qilaman. Kunimni ertalab soat 7 da turishdan boshlayman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ого, довольно рано. Что делаешь сразу после подъёма?",
          uz: "Voy-buy, ancha erta ekan. Turganingdan keyin darrov nima qilasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Сначала я занимаюсь утренней зарядкой минут 20, а потом иду на кухню готовить завтрак.",
          uz: "Avval taxminan 20 daqiqa ertalabki badantarbiya bilan shug’ullanaman, keyin nonushta tayyorlash uchun oshxonaga boraman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Интересно. А что обычно на завтрак?",
          uz: "Qiziqarli. Odatda nonushtaga nima yeysan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я стараюсь кушать что-то лёгкое, например, овсяную кашу.",
          uz: "Men engil narsa iste'mol qilishga harakat qilaman, masalan, suli yormasidan bo’tqa.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А что делаешь после завтрака?",
          uz: "Nonushtadan keyin nima qilasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "После завтрака я обычно иду на учёбу.",
          uz: "Nonushtadan keyin o'qishga boraman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как долго ты учишься?",
          uz: "Qancha vaqt  o'qiysan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "До обеда, примерно до часа дня. Потом перерыв на обед.",
          uz: "Tushlikgacha, tahminan kunduzgi soat birgacha. Keyin tushlik uchun tanaffus qilaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Что делаешь после учёбы?",
          uz: "O'qishdan keyin nima qilasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Люблю прогуляться, если позволяет погода. Это помогает расслабиться.",
          uz: "Ob-havo imkon bersa, sayr qilishni yaxshi ko'raman. Bu dam olishga yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А мне для этого нравится почитать или посмотреть сериал. Когда ложишься спать?",
          uz: "Buning uchun men o'qishni yoki serial tomosha qilishni yaxshi ko'raman. Qachon uxlashga yotasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Стараюсь ложиться не позже 11 вечера.",
          uz: "Kechki soat 23:00 dan kechiktirmay uxlashga harakat qilaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо, что поделился своим распорядком. Очень интересно было узнать, как устроен твой день.",
          uz: "Kun tartibing bilan tanishtirganing uchun rahmat. Sening kuning qanday tashkil qilinganini bilish juda qiziq edi.",
        },
      ],
    },

    {
      id: 7,
      theme: "Mamlakatlar va millatlar",
      theme_ru: "Страны и национальности",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! В какой стране тебе хотелось бы побывать?",
          uz: "Salom! Qaysi davlatga tashrif buyurishni xohlaysan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Я всегда мечтал побывать в Италии.",
          uz: "Salom! Men doimo Italiyaga borishni orzu qilardim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "И я. Там такая красивая природа и невероятная кухня.",
          uz: "Men ham. U yerda go'zal tabiat va aql bovar qilmaydigan taomlar bor.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А еще итальянцы очень гордятся своей кухней, и я хотел бы тоже ее попробовать.",
          uz: "Yana italiyaliklar o'zlarining taomlari bilan juda faxrlanadilar va men ham uni ta’tib ko'rmoqchiman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А мне всегда хотелось побывать в Японии.",
          uz: "Men doim Yaponiyaga borishni xohlardim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Почему?",
          uz: "Nega?",
        },
        {
          gender: "male",
          person: "2",
          ru: "У них такое интересное сочетание современности и традиций.",
          uz: "Ularda shunaqangi  qiziqarli uyg'unligi bor: zamonaviylik va an'anaviylikni.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Верно, японцы очень уважают свою культуру. А как насчет языкового барьера?",
          uz: "To‘g‘ri, yaponlar o‘z madaniyatini juda hurmat qilishadi. Lekin til to'sig'ichi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это, конечно, сложность. Но я бы купил разговорник.",
          uz: "Bu, albatta,  qiyinchilik. Lekin men so’zlashuv kitobini sotib olardim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А какие страны ты уже посещал? Где тебе больше всего понравилось?",
          uz: "Qaysi mamlakatlarga borgansan? Qayerda senga ko'proq yoqqan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Был в Германии и Франции. Очень понравилась Германия за её порядок и чистоту.",
          uz: "Germaniya va Fransiyada bo‘lganman. Menga Germaniya tartib va ​​tozaligi uchun juda yoqdi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Интересно, я всегда хотел посетить Францию. Что тебе понравилось в ней?",
          uz: "Qiziq, men doimo Frantsiyaga borishni xohlardim. Uning nimasi senga yoqdi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Во Франции меня впечатлила архитектура и искусство.",
          uz: "Fransiyada arxitektura va san’at menda katta taassurot qoldirdi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Мне кажется, французы очень дружелюбные.",
          uz: "Menimcha, frantsuzlar juda samimiy.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Так и есть! Надеюсь, у тебя получится как-нибудь побывать во Франции и узнать самому.",
          uz: "Ha shunaqa! Umid qilamanki, sen qachondir Frantsiyaga borib, o'zing bilib olishing  mumkin.",
        },
      ],
    },

    {
      id: 8,
      theme: "Vaqt. Soat nechi?",
      theme_ru: "Время. Сколько времени?",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Скажи, пожалуйста, сколько сейчас времени?",
          uz: "Iltimos. ayt-chi, xozir soat nechi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "По моим часам сейчас без пятнадцати два.",
          uz: "Mening soatimga ko'ra, hozir o’n beshtakam ikki.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ого, а я думал, что еще утро. Время летит незаметно.",
          uz: "Voy, men hali ertalab deb o'ylabman. Vaqt tez o'tmoqda.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, особенно когда много работы. Ты не забыл, что у нас в половину третьего встреча?",
          uz: "Ha, ayniqsa ish ko'p bo'lganda. Soat ikki  yarimda uchrashuvimiz borligini unutmadingmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Cовсем вылетело из головы. Спасибо, что напомнил.",
          uz: "Xayolimdan butunlay chiqib ketibdi. Eslatganing uchun rahmat.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Не за что. Как ты думаешь, успеешь подготовиться?",
          uz: "Arzimaydi. Nima deb o’ylaysan, tayyorlanishga ulgurasanmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Думаю, да. Остался час, это должно быть достаточно.",
          uz: "Menimcha. ha. Bir soat qoldi. Bu yetarli bo’lishi kerak.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отлично. А как ты обычно отслеживаешь время?",
          uz: "Zo’r. Vaqtni odatda  qanday kuzatasan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Обычно я использую часы и напоминания в телефоне.",
          uz: "Men odatda telefonimdagi  soat va eslatmalardan foydalanaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я тоже, но важные вещи я предпочитаю записывать в планировщик и ставить будильники.",
          uz: "Men ham, lekin  muhim narsalarni rejalashtiruvchiga yozib qo'yish va budilnik o'rnatishni afzal ko'raman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это действительно помогает не забывать о важных делах.",
          uz: "Bu haqiqatan ham muhim narsalarni unutmaslikka yordam beradi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Советую. Это очень удобно и помогает быть организованным.",
          uz: "Maslahat beraman. Bu juda qulay va tartibli bo’lishga yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо за совет! Уже два часа, мне пора идти готовиться ко встрече.",
          uz: "Maslahating uchun rahmat! Soat ikki bo'ldi, borib, yig'ilishga tayyorgarlik ko'rishim kerak.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Увидимся через полчаса!",
          uz: "Yarim soatdan keyin ko'rishamiz!",
        },
        {
          gender: "male",
          person: "1",
          ru: "Увидимся! Теперь я точно не опоздаю.",
          uz: "Ko'rishguncha! Endi men aniq kechikmayman.",
        },
      ],
    },

    {
      id: 9,
      theme: "Shaharda",
      theme_ru: "В городе",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Слушай, а ты знаешь, как пройти к библиотеке?",
          uz: "Menga qara, kutubxonaga qanday borishni bilasanmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, конечно. Иди прямо до перекрестка, затем поверни налево и пройди еще два дома.",
          uz: "Ha albatta. Chorrahaga yetguncha to‘g‘ri yur, so‘ng chapga buril va yana ikkita uydan o‘t.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо большое!",
          uz: "Katta rahmat!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Библиотека будет справа. Ты не пройдешь мимо.",
          uz: "Kutubxona o'ng tomonda bo'ladi. Sen yonidan o'tib ketmaysan.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А рядом с библиотекой есть какие-нибудь кафе?",
          uz: "Kutubxona yaqinida bironta kafe bormi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, есть одно очень уютное кафе прямо напротив библиотеки.",
          uz: "Ha, kutubxonaning ro'parasida bitta juda shinam  kafe bor.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Здорово, обязательно загляну туда. Скажи, а как лучше добраться до музея?",
          uz: "Zo’r,  men u yerga albatta kirib o’taman. Ayt-chi, muzeyga qanday  borish qulayroq?",
        },
        {
          gender: "male",
          person: "2",
          ru: "До музея удобнее всего доехать на автобусе номер пять. Остановка прямо у магазина электроники.",
          uz: "Eng qulay muzeyga beshinchi avtobusda borish. To'xtash joyi to’g’ri elektronika do'konning yonida.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо за подсказку. А не знаешь, работает ли музей в понедельник?",
          uz: "Maslahating uchun rahmat. Bilmaysanmi, dushanba kuni muzey ishlaydimi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "К сожалению, в понедельник музей обычно закрыт. Лучше планировать посещение на другой день.",
          uz: "Afsuski,  dushanba kuni muzey odatda yopiq bo’ladi. Borishni  boshqa kunga rejalashtirganing ma'qul.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ясно, буду иметь в виду.",
          uz: "Albatta, buni yodda tutaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Но там рядом есть парк. Там очень красиво в любое время года.",
          uz: "Ammo u yerning yaqinida park bor. Yilning istalgan vaqtida u erda juda chiroyli.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Отлично, я обожаю гулять на свежем воздухе. Спасибо за советы!",
          uz: "Zo’r, men toza havoda sayr qilishni juda yaxshi ko'raman. Maslahatlaring uchun rahmat!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Пожалуйста, приятной прогулки!",
          uz: "Marhamat,  sayr yoqimli bo’lsing!",
        },
      ],
    },

    {
      id: 10,
      theme: "Qancha turadi?",
      theme_ru: "Сколько стоит?",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Здравствуйте! Скажите, пожалуйста, сколько стоит этот свитер?",
          uz: "Assalom alaykum! Iltimos, ayting-chi, bu sviter qancha turadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Добрый день! Этот свитер стоит три тысячи рублей.",
          uz: "Hayrli kun! Bu sviter uch ming rubl turadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А у вас есть скидки на одежду сейчас?",
          uz: "Hozir kiyim-kechaklarga chegirmalaringiz bormi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, у нас действует акция: при покупке двух вещей – скидка на вторую вещь.",
          uz: "Ha, bizda hozir aksiya ketayapti: agar siz ikkita mahsulot sotib olsangiz, ikkinchi mahsulotga chegirma bor.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Понятно. А сколько стоит вон та куртка?",
          uz: "Tushunarli. U yerdagi kurtka qancha turadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Та куртка стоит пять тысяч рублей.",
          uz: "U kurtka besh ming rubl turadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Хорошо.",
          uz: "Yaxshi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Если вы возьмете свитер и куртку, стоимость свитера будет полторы тысячи рублей.",
          uz: "Agar siz sviter va kurtka olsangiz, sviterning narxi bir yarim ming rubl bo'ladi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отлично! А сколько примерно стоят перчатки?",
          uz: "Ajoyib! Qo'lqoplar taxminan qancha turadi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Перчатки стоят от одной тысячи до двух тысяч рублей, в зависимости от материала.",
          uz: "Qo'lqoplar materialga qarab mingdan ikki ming rublgacha turadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А сколько стоит вот эта шапка?",
          uz: "U yerdagi qalpoq qancha turadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Восемьсот рублей.",
          uz: "Sakkiz yuz rubl.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо за помощь! Я примерю эти вещи и приму решение.",
          uz: "Yordamingiz uchun rahmat! Men bu narsalarni kiyib  ko'raman va qaror qabul qilaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Не за что! Если возникнут вопросы, обращайтесь. Будем рады помочь.",
          uz: "Arzimaydi! Agar sizda biron bir savol tug’ilsa, murojaat qiling. Yordam berishdan xursand bo'lamiz.",
        },
      ],
    },

    {
      id: 11,
      theme: "Oziq-ovqat do'konida",
      theme_ru: "В продуктовом магазине",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Что планируешь купить сегодня?",
          uz: "Salom! Bugun nimani sotib olishni rejalashtiryapsan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Думаю, возьму овощи и фрукты.",
          uz: "Salom! Men sabzavot va mevalarni olaman deb o'ylayman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Звучит здорово! А как насчет мяса или рыбы?",
          uz: "Ajoyib eshitiladi! Go'sht yoki baliqchi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, наверное, стоит взять и мясо. Какой вид посоветуешь?",
          uz: "Ha, go'sht ham olish kerak, shekilli. Qanaqasini  tavsiya qilasan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Может быть, курицу или говядину?",
          uz: "Balki tovuq yoki mol go'shti?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошая идея. А какие фрукты ты предпочитаешь?",
          uz: "Qaysi mevalarni afzal ko'rasan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Обычно беру яблоки, бананы и апельсины.",
          uz: "Men odatda olma, banan va apelsinlarni olaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А как насчет овощей?",
          uz: "Sabzavotlar-chi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Предпочитаю помидоры и огурцы.",
          uz: "Pomidor va bodringni afzal ko'raman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отличный выбор! А что насчет продуктов для завтрака?",
          uz: "Nonushta uchun oziq-ovqat mahsulotlarchi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Возьму йогурт и мюсли.",
          uz: "Yogurt va mussli olaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Звучит как полезный завтрак. А что еще планируешь купить?",
          uz: "Yana nimani sotib olishni rejalashtiryapsan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Смотри, вот этот хлеб выглядит хорошо.",
          uz: "Qara, ko’rinishidan bu non yaxshiga o’xshaydi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, очень свежий, я тоже возьму. Пойдем кассе?",
          uz: "Ha, endi yopilgan, men ham olaman. Kassaga boramizmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Давай. Надеюсь, не будет очереди.",
          uz: "Kel. Umid qilamanki, navbat bo'lmaydi.",
        },
      ],
    },

    {
      id: 12,
      theme: "Kiyim do'konida",
      theme_ru: "В магазине (Одежда)",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Здравствуйте! Чем я могу вам помочь?",
          uz: "Assalomu alaykum! Sizga qanday yordam berishim mumkin?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Добрый день. Я ищу новую рубашку на свидание.",
          uz: "Hayrli kun. Uchrashuv uchun yangi ko'ylak qidiryapman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Какой стиль вы предпочитаете?",
          uz: "Qaysi stilni afzal ko'rasiz?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Классические модели.",
          uz: "Klassik modellar.",
        },
        {
          gender: "male",
          person: "1",
          ru: "У нас есть несколько вариантов. Посмотрите здесь.",
          uz: "Bizda bir nechta variant bor. Mana bu yerda qarang.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спасибо! А что скажете об этой синей?",
          uz: "Rahmat! Bu ko'k rangli haqida nima deysiz?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Думаю, вам будет к лицу этот цвет. А может быть, попробуете еще черную?",
          uz: "Menimcha, bu rang sizga yarashadi. Balkim  qora rangni ham kiyib ko’rasiz?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Наверное, она будет более формальной. А как насчет размера?",
          uz: "Menimcha, u rasmiy  ko’rinadi. O’chamlari bormi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Мне кажется, что L вам подойдет.",
          uz: "Mening fikrimcha, L sizga mos keladi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Давайте померяем.",
          uz: "Keling, kiyib ko'raylik.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как вам длина рукавов?",
          uz: "Yenglarning uzunligi sizga to’g’ri keladimi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Немного коротковаты. Есть ли другие размеры?",
          uz: "Bir oz kaltaroq. Boshqa o'lchamlari bormi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, у нас есть размер XL. Попробуйте эту.",
          uz: "Ha, bizda XL o'lcham bor. Bunisini kiyib ko’ring.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Она сидит отлично! Спасибо за помощь.",
          uz: "Juda yarashdi! Yordamingiz uchun rahmat.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Рад был помочь! Я отнесу эту рубашку на кассу.",
          uz: "Yordam berganimdan hursandman! Men bu ko'ylakni kassaga olib borib beraman.",
        },
      ],
    },

    {
      id: 13,
      theme: "Bankda",
      theme_ru: "В банке",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Здравствуйте! Я хотел бы обменять доллары на рубли.",
          uz: "Salom! Men dollarni rublga almashtirmoqchi edim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Конечно, сколько вы хотите обменять?",
          uz: "Albatta, qancha almashtirmoqchisiz?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Пятьсот долларов, пожалуйста.",
          uz: "Besh yuz dollar, iltimos.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошо, вот ваша сумма в рублях. Могу ли я помочь вам чем-то еще?",
          uz: "Mayli, mana sizning pulingizni rubldagi qiymati. Sizga yana yordamim kerakmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, я хотел бы положить деньги на депозит.",
          uz: "Ha, men pulimni omonatga qo'ymoqchiman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Какую сумму вы хотели бы положить и на какой срок?",
          uz: "Qancha pul qo'ymoqchisiz va qanaqa muddatga?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Десять тысяч рублей на год.",
          uz: "O'n ming rubl bir yilga.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отлично, у нас есть несколько вариантов депозитов. Выберите удобный для вас.",
          uz: "Juda yaxshi, bizda bir nechta omonat turlari mavjud. Siz uchun qulay bo'lgan birini tanlang.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я выберу с фиксированной ставкой. Какие документы мне нужны?",
          uz: "Belgilangan tarif bilan tanlayman. Menga qanaqa hujjatlar kerak?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Вам нужен паспорт и ИНН.",
          uz: "Sizga pasport va INN kerak.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Вот, пожалуйста. Сколько времени займет оформление?",
          uz: "Mana, marhamat. Ro'yxatdan o'tishga qancha vaqt ketadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Около 20 минут. Пока я заполню все формы, можете подождать.",
          uz: "Taxminan 20 daqiqa. Men barcha shakllarni to'ldirgunimcha kutib turishingiz mumkin.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Хорошо, спасибо. Я подожду.",
          uz: "Yaxshi raxmat. Men kutib turaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Все готово, ваш депозит оформлен. Получите документы и карту.",
          uz: "Hammasi tayyor, omonatingiz rasmiylashtirildi. Hujjatlaringizni va kartangizni oling.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Благодарю вас за помощь. Хорошего дня!",
          uz: "Yordamingiz uchun minnatdorman. Xayrli kun!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Вам тоже хорошего дня!",
          uz: "Sizning ham kuningiz xayrli o'tsin!",
        },
      ],
    },

    {
      id: 14,
      theme: "Transport",
      theme_ru: "Транспорт",
      dialog: [
        {
          gender: "male",
          person: 1,
          ru: "Какой транспорт ты предпочитаешь?\nЯ чаще всего пользуюсь общественным транспортом. А ты?",
          uz: "Qaysi transport turini afzal ko'rasan?\nKo'pincha jamoat transportidan foydalanaman. Senchi?",
        },
        {
          gender: "male",
          person: 2,
          ru: "Я предпочитаю автомобиль. Это удобно и быстро.\nДа, согласен. Но иногда общественный транспорт бывает удобнее.",
          uz: "Men yengil mashinani afzal ko'raman. Bu qulay va tez.\nHa roziman. Lekin ba'zida jamoat transporti qulayroq bo’ladi.",
        },
        {
          gender: "male",
          person: 1,
          ru: "Точно. Я иногда езжу на велосипеде, чтобы избежать пробок и оставаться в форме.\nЗвучит здорово!",
          uz: "To’g’ri. Men ba'zan tirbandlikdan qochish va sog'lom bo’lish uchun velosipedda yuraman.\nZo’r-ku!",
        },
        {
          gender: "male",
          person: 2,
          ru: "Велосипед - это не только экологичный, но и здоровый вид транспорта.\nКак часто ты пользуешься общественным транспортом?",
          uz: "Velosiped nafaqat ekologik toza, balki sog‘lom transport turidir.\nJamoat transportidan tez-tez  foydalanasanmi?",
        },
        {
          gender: "male",
          person: 1,
          ru: "Почти каждый день. Мне удобно добираться до работы на автобусе или метро.\nА за что ты любишь автомобиль?",
          uz: "Deyarli har kuni. Menga ishga avtobus yoki metroda borish  qulay.\nSen nima uchun yengil mashinani  yaxshi ko'rasan?",
        },
        {
          gender: "male",
          person: 2,
          ru: "За свободу перемещения и комфорт.\nЭто верно. Хотя общественный транспорт тоже имеет свои плюсы, например.",
          uz: "Harakat erkinligi va qulayligi uchun.\nBu to `g` ri. Lekin, jamoat transporti ham o'zining afzalliklariga ega.",
        },
        {
          gender: "male",
          person: 1,
          ru: "Каждый вид транспорта подходит для определенных ситуаций.\nТочно. Главное выбирать то, что удобно и соответствует целям поездки.",
          uz: "Har bir transport turi aniq bir vaziyatlarga mos keladi.\nJuda to’g’ri. Muhimi,  qulay va sayohat maqsadiga mos kelganini tanlash.",
        },
        {
          gender: "male",
          person: 2,
          ru: "Согласен. Но я всё же склоняюсь к автомобилю как к основному средству передвижения.",
          uz: "Gapinga qo’shilaman. Lekin men baribir asosiy transport vositasi sifatida yengil mashinani afzal ko’raman.",
        },
      ],
    },

    {
      id: 15,
      theme: "Ob-havo. Fasllar",
      theme_ru: "Погода. Времена года.",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Как тебе погода сегодня?",
          uz: "Senga bugungi ob-havo yoqadimi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, сегодня действительно прекрасный день.",
          uz: "Ha, bugun chindan ham go'zal kun.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Лето - мое любимое время года.",
          uz: "Yoz -mening sevimli faslim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я тоже предпочитаю лето. Люблю тепло и солнце.",
          uz: "Men ham yozni afzal ko'raman. Men issiq havoni va quyoshni yaxshi ko'raman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А зимой ты катаешься на лыжах?",
          uz: "Qishda chang'i uchasizmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Нет, лыжи – это не моё.",
          uz: "Yo'q, chang'i uchish menga yoqmaydi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А как насчет осени? Что тебе нравится в этом времени года?",
          uz: "Kuz-chi? Yilning bu faslida senga nima yoqadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Осень мне нравится красотой природы и прохладным воздухом.",
          uz: "Kuz menga tabiatning go‘zalligi va havosini salqinligi yoqadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, осенью можно насладиться красочными листьями и уютом дома.",
          uz: "Ha, kuzda rang-barang barglar va shinam uy qulayliklaridan bahramand bo'lish mumkin.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А весна - время пробуждения природы.",
          uz: "Bahor esa tabiatning uyg'onish davri.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Для меня весна - это время надежды, новых начинаний и свежести.",
          uz: "Men uchun bahor umid, yangilanish va mussofalik davri.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, весной все оживает после зимней спячки.",
          uz: "Ha, bahorda barcha narsalar qish uyqusidan uyg’onadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Хочется больше времени проводить на улице, гулять, заниматься спортом.",
          uz: "Ko'proq vaqtimni ko’chada o'tkazish, sayr qilish, sport bilan shug'ullanishni hohlayman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Если погода хорошая.",
          uz: "Agar ob-havo yaxshi bo'lsa.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это правда. Но я принимаю погоду такой, какая она есть, и стараюсь радоваться каждому дню.",
          uz: "Bu to'g'ri. Lekin men ob-havoni barcha ko’rinishida qabul qilaman va har bir kundan zavq olishga intilaman.",
        },
      ],
    },

    {
      id: 16,
      theme: "Mening uyim, mening kvartiram",
      theme_ru: "Мой дом, моя квартира",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Расскажи, как ты живешь? В квартире или в доме?",
          uz: "Salom! Ayt-chi, qayerda yashaysan? Xonadondami yoki hovli uydami?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я живу в квартире. У меня двухкомнатная. А ты?",
          uz: "Men xonadonda yashayman. Mening ikki xonali xonadonim bor. Senchi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "У меня тоже квартира, но однокомнатная.",
          uz: "Mening ham xonadonim bor, lekin u bir xonali.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А какой у тебя район?",
          uz: "Qaysi hududda?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Мой район тихий и зеленый. Рядом парк, магазины, удобно.",
          uz: "Men yashaydigan hudud tinch va yashil. Yaqinida park, do'konlar bor, qulay.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Звучит замечательно! У меня тоже неплохой район, но шумновато.",
          uz: "Juda yaxshi! Mening hududim ham yaxshi, lekin biroz shovqinli.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Шумные районы тоже имеют свои плюсы. А как соседи у тебя?",
          uz: "Shovqinli joylarning ham o'ziga xos afzalliklari bor. Qo'shnilaring qanaqa?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Соседи дружелюбные, никогда не шумят.",
          uz: "Qo'shnilar do'stona, ular hech qachon shovqin qilishmaydi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А какая обстановка в твоей квартире?",
          uz: "Sening xonadoning qanday jihozlangan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "У меня уютно и светло. Много растений, книг, создаю уютный уголок.",
          uz: "Menikida qulay va yorug’. O'simliklar, kitoblar ko’p , shinam burchak yarataman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я тоже стараюсь создать у себя комфортное пространство. У тебя много мебели?",
          uz: "Men ham uyimda yashashga qulay joy yaratishga harakat qilaman. Senda mebel ko’pmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Не очень. Я стараюсь подбирать предметы мебели, которые будут и красивыми, и удобными.",
          uz: "Unchalik emas. Men chiroyli va qulay bo'lgan mebel turlarini tanlashga harakat qilaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А я люблю, когда дома просторно и мало вещей.",
          uz: "Uyim keng va narsalar kam bo’lishini yaxshi ko'raman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Главное, чтобы тебе было комфортно.",
          uz: "Muhimi, o'zingni qulay his qilashdir.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Точно! Чтобы атмосфера дома помогала расслабиться и отдохнуть.",
          uz: "Bu aniq! Uydagi muhit o’zini yengil his qilishga va dam olishga yordam berishi kerak.",
        },
      ],
    },
    {
      id: 17,
      theme: "Kvartirani ijaraga olish",
      theme_ru: "Аренда квартиры",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Ты ищешь квартиру?",
          uz: "Salom! Kvartira qidiryapsanmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, ищу. Мне нужно снять и съехать до конца месяца.",
          uz: "Ha, qidiryapman. Oy oxirigacha ijaraga olib, ko‘chib o‘tishim kerak.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я знаю одну хорошую квартиру в центре города.",
          uz: "Men shahar markazida bitta yaxshi kvartirani bilaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Сколько за неё просят?",
          uz: "Qancha so'rayaptilar?",
        },
        {
          gender: "male",
          person: "1",
          ru: "40 тысяч в месяц.",
          uz: "oyiga 40 ming.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это немного дорого для меня.",
          uz: "Bu men uchun biroz qimmat.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Можно попробовать поторговаться с хозяином.",
          uz: "Egasi bilan savdolashishga harakat qilib ko’rish mumkin.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошая идея. А какие условия аренды?",
          uz: "Ijara shartlari qanaqa?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Квартира полностью меблирована, есть все необходимое.",
          uz: "Kvartira to'liq jihozlangan, senga kerak bo'lgan hamma narsa mavjud.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это уже хорошо. А сколько коммунальные услуги?",
          uz: "Kommunal xizmatlar qancha turadi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Включены в стоимость аренды.",
          uz: "Ijara narxiga kiritilgan.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отлично. Можешь дать мне контакты хозяина?",
          uz: "Menga egasining aloqa ma'lumotlarini bera olasanmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Конечно, я отправлю тебе номер телефона.",
          uz: "Albatta, senga telefon raqamini yuboraman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спасибо большое! Я позвоню и узнаю подробности.",
          uz: "Katta rahmat! Men qo'ng'iroq qilaman va tafsilotlarni bilib olaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Не за что, рад был помочь. Удачи с поисками!",
          uz: "Arzimaydi, yordam berganimdan xursandman. Qidiruvlaringizga omad!",
        },
      ],
    },
    {
      id: 18,
      theme: "Turizm va sayohat",
      theme_ru: "Туризм и путешествие",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Какие планы на выходные?",
          uz: "Salom! Dam olish kunlariga qanday rejalaring  bor?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Привет! Планирую поехать в Санкт-Петербург.",
          uz: "Salom! Sankt-Peterburgga borishni rejalashtiryapman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "О, звучит интересно! Что тебя привлекает в этом городе?",
          uz: "Oh, bu qiziq! Seni bu shaharda nima jalb qiladi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Мне хочется увидеть Эрмитаж, Петергоф, Петропавловскую крепость.",
          uz: "Men Ermitaj, Petergof, Petropavlovsk qal'asini ko'rmoqchiman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Классический маршрут! А где собираешься остановиться?",
          uz: "Klassik marshrut! Qayerda to’htashni rejallashtirayapsan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Забронировал номер в центре города, чтобы было удобно осматривать достопримечательности.",
          uz: "Diqqatga sazovor joylarni tomosha qilish  qulay bo'lishi uchun shahar markazidan mehmonxonani bron qildim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "У тебя уже есть планы на каждый день?",
          uz: "Har bir kun uchun rejang bormi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, хочу посетить музеи, прогуляться по Невскому проспекту, съездить в Пушкин.",
          uz: "Ha, men muzeylarga borishni, Nevskiy prospekti bo'ylab sayr qilishni, Pushkinga borib kelishni xohlayman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Звучит как отличный отдых! Надеюсь, будет хорошая погода!",
          uz: "Ajoyib ta'tilga o'xshaydi! Umid qilamanki, ob-havo yaxshi bo’ladi!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Надеюсь тоже! А ты собираешься куда-то путешествовать?",
          uz: "Men ham  umid qilaman! Seni biror joyga sayohatga  borish niyating bormi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Нет, пока нет планов. Может быть, подумаю о поездке, когда у меня будет отпуск.",
          uz: "Yo'q, hozircha rejalarim yo'q. Balki, ta’tilga chiqqanimda sayohat haqida o’ylab ko’raman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это здорово! А скоро у тебя отпуск?",
          uz: "Bu ajoyib! Tez orada ta'tilga chiqasanmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Через два месяца. Мне тоже хотелось бы съездить в путешествие.",
          uz: "Ikki oydan keyin. Men ham sayohatga borib kelmoqchiman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Путешествия всегда приносят массу положительных эмоций.",
          uz: "Sayohat har doim juda ko'p ijobiy his-tuyg'ularni olib keladi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Согласен! Надеюсь, что и ты проведешь время весело и интересно в Санкт-Петербурге.",
          uz: "Fikringa qo’shilaman! Umid qilamanki, sen ham Sankt-Peterburgda vaqtinni quvnoq va qiziqarli  o'tkazasan.",
        },
      ],
    },
    {
      id: 19,
      theme: "Aeroportda",
      theme_ru: "В аэропорту",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Как прошел твой полет?",
          uz: "Salom! Parvoz qanday o'tdi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Здравствуй! Все прошло отлично, спасибо. А твой рейс?",
          uz: "Salom! Hammasi ajoyib o'tdi, rahmat. Sening  reysingchi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Тоже без проблем. Как долго ждал посадки?",
          uz: "Muammosiz. Samolyotga o’tirishni qancha kutding?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Не очень долго, всего около полутора часа.",
          uz: "Unchalik uzoq emas, atigi bir yarim soatcha.",
        },
        {
          gender: "male",
          person: "1",
          ru: "У меня был пересадка, пришлось бегать по терминалу.",
          uz: "Menda peresadka bor edi, terminal bo’ylab yugurishga to’g’ri keldi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это всегда неприятно. А какие планы у тебя в этом городе?",
          uz: "Bu har doim yoqimsiz. Bu shaharda qanday rejalaring bor?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Пока просто хочу осмотреться, может быть, посетить какие-то достопримечательности.",
          uz: "Hozircha men atrofni ko’rmoqchiman, balki diqqatga sazovor joylarga borarman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошая идея. Ты уже получил багаж?",
          uz: "Sen yukingni olib bo’ldingmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Нет, сейчас пойду за ним.",
          uz: "Yo'q,  hozir  olishga boraman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А я выпью кофе, а потом закажу такси в город.",
          uz: "Men qahva ichaman, keyin shaharga taksi buyurtma berfmfn.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я планирую воспользоваться общественным транспортом. Я видел, есть переход в метро прямо из аэропорта.",
          uz: "Men jamoat transportidan foydalanishni rejalashtirayapman. Aeroportdan to'g'ridan-to'g'ri metroga o'tish yo’lagi borligini ko'rdim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, это правда. Но можно воспользоваться скоростным поездом, он быстрее.",
          uz: "Ha, bu to’g’ri. Lekin sen tezyurar poyezddan foydalanishing mumkin, u tezroq.",
        },
        {
          gender: "male",
          person: "1",
          ru: "На нем можно доехать до центра города?",
          uz: "U bilan  shahar markaziga yetib borsa bo’ladimi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, но билеты немного дороже, чем на метро.",
          uz: "Ha, lekin chiptalar metrodan biroz qimmatroq.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Большое спасибо за информацию! Я подумаю, какой вариант подойдет лучше.",
          uz: "Ma'lumot uchun katta rahmat! Qaysi variant to’g’ri kelishini o'ylab ko'raman.",
        },
      ],
    },
    {
      id: 20,
      theme: "Mehmonga, teatrga, kinoga taklif",
      theme_ru: "Приглашение в гости, в театр, в кино.",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Привет! Как дела? Слушай, у меня есть билеты в театр на эту пятницу. Хочешь пойти со мной?",
          uz: "Salom! Ishlaringiz qalay? Eshit, menda bu jumaga teatr chiptalari bor. Men bilan borishni xohlaysizmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "О, это замечательно! Конечно, я с удовольствием пойду в театр с тобой.",
          uz: "Oh, bu ajoyib! Albatta, men bajonidil sen bilan teatrga boraman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Отлично! Тогда давай встретимся у театра за полчаса до начала спектакля.",
          uz: "Juda zo’r! Unda spektakl boshlanishidan yarim soat oldin teatrda uchrashaylik.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А во сколько он начинается?",
          uz: "U soat nechada boshlanadi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "В семь часов, значит, мы можем встретиться в половину седьмого.",
          uz: "Soat yettida, demak, yetti yarimda uchrashishimiz mumkin.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Договорились. Какой спектакль мы будем смотреть?",
          uz: "Kelishdik. Qanaqa spektakl tomosha qilamiz?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это будет классическая комедия 'Кошка на раскаленной крыше'.",
          uz: "Bu 'Issiq tunuka tomidagi mushuk' klassik komediyasi bo'ladi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Звучит интересно! Я никогда не видел этот спектакль.",
          uz: "Qiziqarli eshitilayapti! Men bu spektaklni hech qachon ko'rmaganman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ты точно останешься доволен, он очень занимательный.",
          uz: "Senga  albatta yoqadi, u juda qiziq.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А после театра можем сходить в кафе.",
          uz: "Teatrdan keyin esa kafega borishimiz mumkin.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Замечательная идея! Я уже предвкушаю этот вечер.",
          uz: "Ajoyib fikr! Men  bu oqshomni intiqlik bilan kutyapman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Тогда договорились! Спасибо за приглашение, я уверен, что будет замечательно.",
          uz: "Unda kelishib oldik! Taklif uchun rahmat,  ishonamanki ajoyib bo’ladi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Не за что! Всегда рад провести время в компании такого приятного человека как ты.",
          uz: "Arzimaydi! Sendek yaxshi inson bilan birga vaqt o'tkazishdan doim xursandman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Жду нашей встречи в пятницу.",
          uz: "Juma kungi uchrashuvimizni kutaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "До встречи! Пока!",
          uz: "Ko'rishguncha! Xayr!",
        },
      ],
    },
    {
      id: 21,
      theme: "Oshxona. Restoran",
      theme_ru: "Кухня. Ресторан.",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Здравствуйте! Мне, пожалуйста, пиццу и салат.",
          uz: "Salom! Menga pizza va salat bering, iltimos.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Добрый день! Отличный выбор. Что будете пить?",
          uz: "Hayrli kun! Ajoyib tanlov. Nima ichasiz?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я возьму воду с газом, пожалуйста.",
          uz: "Men gazlangan suv olaman, mumkin bo’lsa.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошо, я сейчас принесу заказ.",
          uz: "Yaxshi, buyurtmani hozir olib kelaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо! А сколько времени уйдёт на приготовления?",
          uz: "Rahmat! Tayyorlashga  qancha vaqt ketadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Пицца будет готова через 15 минут, салат - сразу.",
          uz: "Pissa 15 daqiqada tayyor bo'ladi, salat - xozirroq.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Отлично, спасибо за информацию.",
          uz: "Ajoyib, ma'lumot uchun rahmat.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Пожалуйста. А какую вы хотите пиццу - на тонком или толстом тесте?",
          uz: "Marhamat. Qanday pissa istaysiz - yupqa yoki qalin hamirli?",
        },
        {
          gender: "male",
          person: "1",
          ru: "На тонком, пожалуйста.",
          uz: "Yupqa hamirli, iltimos.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошо, учту ваши пожелания.",
          uz: "Mayli, istaklaringizni inobatga olaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А есть ли у вас десерты?",
          uz: "Pishiriqlaringiz bormi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, у нас есть тирамису и шоколадный фондан.",
          uz: "Ha, bizda tiramisu va shokoladli fondan bor.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Замечательно! Я возьму шоколадный фондан.",
          uz: "Ajoyib! Men shokoladli fondan olaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отличный выбор. Я добавлю его к вашему заказу.",
          uz: "Ajoyib tanlov. Men uni buyurtmangizga qo'shib qo’yaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Большое спасибо!",
          uz: "Katta rahmat!",
        },
      ],
    },
    {
      id: 22,
      theme: "Mening sevimli taomim",
      theme_ru: "Моё любимое блюдо",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Какое твоё любимое блюдо?",
          uz: "Sening sevimli taoming nima?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Мое любимое блюдо - паста карбонара.",
          uz: "Mening sevimli taomim karbonara pastasidir.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я тоже обожаю пасту! Почему именно карбонара?",
          uz: "Men ham pastani yaxshi ko'raman! Nima uchun aynan karbonara?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Мне нравится сочетание сливочного соуса, бекона и пармезана.",
          uz: "Menga qaymoq sousi, bekon va parmesan aralashmasi yoqadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как аппетитно! Ты сам умеешь готовить карбонару?",
          uz: "Qanday mazali! Karbonarani o'zing pishirishni bilasanmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, я научился готовить это блюдо довольно хорошо.",
          uz: "Ha, men bu taomni pishirishni juda yaxshi o'rgandim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А какой секрет приготовления самой вкусной карбонары?",
          uz: "Eng mazali karbonara tayyorlashning siri nimada?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Главное - не пережарить бекон и хорошо размешать соус с яйцами.",
          uz: "Asosiysi, bekonni haddan tashqari pishirmaslik va sousni tuxum bilan yaxshilab aralashtirish.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это точно! Я иногда добавляю еще немного чеснока для аромата.",
          uz: "Bu to’g’ri! Men ba'zan xushbo’ylik uchun yana ozgina  sarimsoq qo'shaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А какую пасту предпочитаешь использовать?",
          uz: "Qaysi makarondan foydalanishni afzal ko'rasan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я обычно выбираю спагетти.",
          uz: "Men odatda spagettini tanlayman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Когда ты в следующий раз планируешь готовить карбонару?",
          uz: "Karbonarani keyingi safar qachon pishirishni rejalashtiryapsan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Возможно, уже на выходных. Хочешь попробовать?",
          uz: "Balki dam olish kunida. Ta’tib ko'rmoqchimisan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "С удовольствием! Обязательно пригласи меня в гости, я попробую.",
          uz: "Bajonidil! Meni albatta mehmohga taklif qil, men ta’tib ko’raman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Отлично! Будет весело провести время за вкусным ужином.",
          uz: "Ajoyib! Mazali kechki ovqat bilan vaqt qiziqarli o’tadi.",
        },
      ],
    },
    {
      id: 23,
      theme: "Tug'ilgan kun. Bayramlar va tabriklar",
      theme_ru: "День рождения. Праздники и поздравления",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Сегодня мой день рождения!",
          uz: "Bugun mening tug'ilgan kunim!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Ого, с днем рождения! Как ты планируешь отмечать?",
          uz: "Voy, tug'ilgan kuning bilan! Qanday nishonlashni rejalashtiryapsan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо! Я хочу устроить небольшую вечеринку дома.",
          uz: "Rahmat! Men uyda kichik ziyofat uyushtirmoqchiman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Кто будет приглашен на вечеринку?",
          uz: "Bayramga kimlar taklif qilinadi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Друзья и близкие, конечно.",
          uz: "Do'stlar va qarindoshlar, albatta.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А что ты хотел бы получить в подарок?",
          uz: "Sovg'a sifatida nimani olishni xohlaysan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Мне было бы приятно получить что-то личное и запоминающееся.",
          uz: "Biron bir shaxsiy va esda qoladigan narsa olsam xursand bo'lardim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Понятно! Я подумаю над подарком для тебя.",
          uz: "Tushunarli! Men senga beradigan sovg'a haqida o'ylab ko’raman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо! А как ты обычно празднуешь свой день рождения?",
          uz: "Rahmat! Sen -chi odatda tug'ilgan kuningni qanday nishonlaysan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я предпочитаю проводить его в уютной обстановке с близкими людьми.",
          uz: "Men uni yaqinlarim bilan shinam joyda o'tkazishni afzal ko'raman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это отличный способ отметить особенный день.",
          uz: "Bu o’zgacha kunni nishonlash uchun ajoyib usul.",
        },
        {
          gender: "male",
          person: "2",
          ru: "День рождения - мой самый любимый праздник.",
          uz: "Tug'ilgan kun mening eng sevimli bayramim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "И мой. Но еще я очень люблю Новый Год.",
          uz: "Meniki ham. Lekin men Yangi yilni ham juda yaxshi ko'raman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Поздравляю тебя с днем рождения еще раз! Пусть этот день будет запоминающимся и радостным.",
          uz: "Yana bir bor tug'ilgan kuning bilan tabriklayman! Bu kun unutilmas va quvonchli bo'lsin.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Большое спасибо! Я очень ценю твои поздравления.",
          uz: "Katta rahmat! Men sening tabriklaringni  juda qadrlayman.",
        },
      ],
    },
    {
      id: 24,
      theme: "Vaqt. Kalendar. Sanoq",
      theme_ru: "Время. Календарь. Счёт",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Как ты обычно планируешь свое время?",
          uz: "Odatda vaqtingni qanday rejalashtirasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я обычно использую календарь для планирования своих дел.",
          uz: "Ishlarimni rejalashtirish uchun odatda kalendardan foydalanaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ты имеешь в виду календарь на телефоне?",
          uz: "Telefondagi kalendarni nazarda tutyapsanmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, но у меня также есть перекидной, это очень удобно и наглядно.",
          uz: "Ha, lekin menda qog’ozlisi ham bor, bu juda qulay va ko’rgazmali.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А как ты отслеживаешь время на протяжении дня?",
          uz: "Kun davomida vaqtni qanday kuzatib borasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я ношу часы на руке, а также всегда можно посмотреть время на телефоне.",
          uz: "Qo’limda soat taqib yuraman, Undan tashqari, har doim telefondan ham vaqtni ko’rish mumkin.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А я не ношу часы. Это помогает тебе не опаздывать?",
          uz: "Men soat taqmayman. Bu senga kechikmaslikka yordam beradimi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, очень. Так очень удобно следить за временем.",
          uz: "Ha juda. Shunday qilib vaqtni kuzatish juda qulay.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А как ты планируешь свои выходные?",
          uz: "Dam olish kunlarini qanday rejalashtirasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Обычно я составляю список дел, которые хочу сделать, и распределяю время на них.",
          uz: "Men odatda qilmoqchi bo'lgan ishlarimni ro'yxatini tuzaman va ularga vaqtni taqsimlayman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Хороший способ организовать свое свободное время.",
          uz: "Bo'sh vaqtinnii tashkil qilishning yaxshi usuli.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А ты отмечаешь важные даты в календаре?",
          uz: "Kalendarda muhim sanalarni belgilaysanmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я обычно делаю пометки или использую цветные метки для выделения.",
          uz: "Men odatda eslatmalar qilaman yoki rangli belgilardan foydalanaman ajratish uchun.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это помогает не пропустить ни одной важной даты.",
          uz: "Bu hech bir muhim sanani o'tkazib yubormaslikka yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, это очень удобно.",
          uz: "Ha, bu juda qulay.",
        },
      ],
    },
    {
      id: 25,
      theme: "Mavzu “Mening sevimli mashg'ulotlarim. Sport\"",
      theme_ru: "Тема «Мои увлечения. Спорт»",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "У тебя есть какие-нибудь увлечения?",
          uz: "Sening sevimli mashg'ulotlaring bormi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я очень люблю заниматься спортом. Это моя страсть.",
          uz: "Men sport bilan shug'ullanishni juda yaxshi ko'raman. Bu mening ishtiyoqim.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А какой вид спорта тебе нравится больше всего?",
          uz: "Qaysi sport turi senga ko'proq yoqadi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я предпочитаю бег. Это отличный способ поддерживать форму и заряжаться энергией.",
          uz: "Men yugurishni afzal ko'raman. Bu sog'likni saqlash va quvvat olishning ajoyib usuli.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Как часто ты бегаешь?",
          uz: "Tez-tez  yugurib turasanmi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Практически каждый день. Утром или вечером, в любую погоду.",
          uz: "Deyarli har kuni. Ertalab yoki kechqurun, har qanday ob-havoda.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ты участвовал когда-нибудь в каких-то соревнованиях?",
          uz: "Sen qandaydir musobaqalarda qatnashganmisan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, я участвовал в нескольких марафонах. Это было невероятно волнующе!",
          uz: "Ha, men bir nechta marafonlarda qatnashganman. Bu nihoyatda hayajonli edi!",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я тоже люблю бегать, но не так активно.",
          uz: "Men ham yugurishni yaxshi ko'raman, lekin u qadar faol emas.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спорт помогает мне расслабиться и собраться мыслями.",
          uz: "Sport menga dam olishimga va fikrlarimni jamlab olishimga yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я тоже люблю спорт.",
          uz: "Men ham sportni yaxshi ko'raman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А какие виды спорта тебе нравятся?",
          uz: "Sportning qaysi  turlari senga yoqadi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я люблю плавать и заниматься йогой.",
          uz: "Men suzishni va yoga bilan shug’ullanishni yaxshi ko'raman.",
        },
        {
          gender: "male",
          person: "2",

          ru: "Хороший выбор. Это помогает сохранять гибкость и укреплять мышцы.",
          uz: "Yaxshi tanlov. Bu egiluvchanlikni saqlashga va mushaklarni kuchaytirishga yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, спорт действительно приносит массу пользы для здоровья.",
          uz: "Ha, sport haqiqatan ham salomatlik uchun juda ko‘p foyda keltiradi.",
        },
      ],
    },
    {
      id: 26,
      theme: 'Mavzu “Tashqi ko‘rinish. Tana a’zolari"',
      theme_ru: "Тема «Внешность. Части тела»",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Тебе нравится моя новая стрижка?",
          uz: "Yangi soch turmagim senga yoqdimi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Очень красиво! Ты всегда так хорошо подбираешь себе прически.",
          uz: "Juda chiroylil! Sen har doim soch turmagini juda yaxshi tanlaysiz.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо!",
          uz: "Rahmat!",
        },
        {
          gender: "male",
          person: "2",
          ru: "А как тебе мой новый свитер?",
          uz: "Mening yangi sviterimchi,  yoqdimi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Он тебе идет и сидит по фигуре! Цвет подходит к твоим глазам.",
          uz: "U senga yarashgan  va  qomatinga mos kelgan! Rangi ko'zlaringa mos.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спасибо! А у тебя новые очки? Они выглядят модно.",
          uz: "Rahmat! Senda yangi ko'zoynakmi? U modaga mos ko'rinadi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, купил недавно.",
          uz: "Ha, yaqinda sotib oldim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Они тебе идут! Они подчеркивают форму лица.",
          uz: "U senga yarashgan! U yuzinni shaklini chiroyli ko’rsatar ekan.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я тоже думаю, что они отлично смотрятся. Но мне не очень нравится форма моего лица.",
          uz: "Men ham, uning ko’rinishi zo’r, deb o’layman. Lekin yuzimning shakli menga unchalik yoqmaydi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Ты всегда выглядишь прекрасно! Ты следишь за собой и это заметно.",
          uz: "Sen ko’rinishig har doim a’lo darajada! Sen  o'zinga qarab yurasan va  bu ko'rinib turibdi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо за комплимент! Я стараюсь. Но иногда хочется что-то изменить в себе.",
          uz: "Iltifoting uchun rahmat! Men harakat qilayapman. Ammo ba'zida  o'zinga  biror narsani o'zgartirishni xohlaysan.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Почему?",
          uz: "Nega?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Нос кажется слишком тонким, а уши - слишком большими.",
          uz: "Menga burnim juda ingichka va quloqlarim juda katta ko'rinayapti.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Если что-то менять, то только больше улыбаться. Улыбка делает любого человека красивее.",
          uz: "Agar biror narsani o'zgartirmoqchi bo’lsang, faqat ko'proq tabassum qil. Tabassum har qanday odamni yanada chiroyliroq qiladi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Ты прав. Улыбка - лучшее украшение.",
          uz: "Sen haqsan. Tabassum eng yaxshi bezakdir.",
        },
      ],
    },
    {
      id: 27,
      theme: "Xarakter xususiyatlari mavzusi",
      theme_ru: "Черты характера",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Какая черта характера для тебя важнее всего?",
          uz: "Sen uchun qaysi xarakter xususiyati muhimroq?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Наверное, честность, потому что это основа любых отношений.",
          uz: "Ehtimol, halollik, chunki bu har qanday munosabatlarning asosidir.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Согласен. А как насчет доброты?",
          uz: "To’g’ri.  Ezgulik haqida nima deyish mumkin?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Доброта делает мир ярче и лучше.",
          uz: "Ezgulik dunyoni yorqinroq va yaxshiroq qiladi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А вот амбициозность? Как ты к ней относишься?",
          uz: "Ambitsiya haqida nima deysan? Unga munosabatig qanday?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я думаю, что амбициозность помогает добиваться целей.",
          uz: "Menimcha, ambitsiya maqsadlarga erishishga yordam beradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Но иногда она может быть вредной, если переходит в жадность.",
          uz: "Lekin ba'zida  ochko'zlikka aylanib qolsa, zararli bo'lishi mumkin.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А как ты относишься к терпимости?",
          uz: "Tolerantlik haqida qanday fikrdasan?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Терпимость - это важное качество, особенно в современном мире.",
          uz: "Tolerantlik- bu muhim fazilatdir, ayniqsa zamonaviy dunyoda.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А насколько для тебя важна скромность?",
          uz: "Kamtarlik sen uchun qanchalik muhim?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это хорошее качество, но все же не стоит быть слишком скромным.",
          uz: "Bu yaxshi fazilat, lekin baribir haddan tashqari kamtar bo'lmaslik kerak.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Скромность - это качество, которое помогает не терять землю под ногами.",
          uz: "Kamtarlik – oyoq ostidagi yerni yo'qotmaslikka yordam beradigan fazilat.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Но больше всего я ценю ответственность.",
          uz: "Lekin men hammasidan ortiq mas'uliyatni qadrlayman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Согласен, это важно. Ответственность - основа надежных отношений и успеха в работе.",
          uz: "Qo’shilaman, bu muhim. Mas'uliyat ishonchli munosabatlar va ishdagi muvaffaqiyatning asosidir.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Но, конечно, все эти качества по-своему важны.",
          uz: "Ammo, bu fazilatlarning barchasi o'ziga xos tarzda muhimdir.",
        },
      ],
    },

    {
      id: 28,
      theme: "Sartaroshxonada” mavzusi",
      theme_ru: "Тема В парикмахерской",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Здравствуйте! Что бы вы хотели?",
          uz: "Salom! Nima istaysiz?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Здравствуйте! Я хочу подстричься и немного освежить образ.",
          uz: "Salom! Men sochimni kesmoqchiman va ko'rinishimni biroz yangilamoqchiman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Конечно, мы рады помочь. Какой именно стиль вы предпочитаете?",
          uz: "Albatta, yordam berishdan xursandmiz. Qaysi uslubni afzal ko'rasiz?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я бы хотел немного подрезать волосы и сделать легкую укладку.",
          uz: "Sochlarimni bir oz qirqib, engil turmak qilmoqchiman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Отлично, давайте начнем. Садитесь, пожалуйста.",
          uz: "Ajoyib, keeling boshlaymiz. Iltimos o'tiring.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спасибо. Вы недавно работаете здесь?",
          uz: "Rahmat. Yaqindan beri shu yerda ishlaysizmi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, но я уже давно занимаюсь этой профессией.",
          uz: "Ha, lekin men anchadan beri bu kasb bilan shug‘ullanaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Это заметно, вы профессионал своего дела. Какие услуги еще у вас есть?",
          uz: "Bu ko'zga tashlanadi, siz o'z ishingizning ustasisiz. Yana qanday xizmatlaringiz bor?",
        },
        {
          gender: "male",
          person: "1",
          ru: "У нас есть окрашивание, укладка, стрижка бороды и многое другое.",
          uz: "Biz rang berish, turmaklash, soqol olish va boshqa ko'p narsalarni taklif qilamiz.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Очень интересно. Мне нравится ваша атмосфера здесь.",
          uz: "Juda qiziq. Menga bu yerdagi muhit yoqayapti.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо, мы стараемся создать уютное и приятное место для наших клиентов.",
          uz: "Rahmat, biz mijozlarimiz uchun qulay va yoqimli joy yaratishga harakat qilamiz.",
        },
        {
          gender: "male",
          person: "2",
          ru: "У вас получается. А что вы можете посоветовать для ухода за волосами?",
          uz: "Sizlar buni uddasidan chiqayapsizlar. Sochni parvarish qilish uchun nimani tavsiya qilishingiz mumkin?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Регулярное увлажнение и использование качественных средств!",
          uz: "Muntazam namlash va sifatli mahsulotlardan foydalanish!",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спасибо за совет. Я обязательно его учту. Готово?",
          uz: "Maslahat uchun rahmat. Men buni albatta hisobga olaman. Tayyormi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, все готово. Посмотрите в зеркало, как вам новый образ?",
          uz: "Ha, hammasi tayyor. Oynaga qarang, yangi qiyofa haqida qanday fikrdasiz?",
        },
      ],
    },

    {
      id: 29,
      theme: "Salomatlik. Sog'lom turmush tarzi",
      theme_ru: "Здоровье. Здоровый образ жизни",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Как ты относишься к здоровому образу жизни?",
          uz: "Sen sog'lom turmush tarziga qanday munosabatdasan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я стараюсь вести здоровый образ жизни, занимаюсь спортом и правильно питаюсь.",
          uz: "Men sog‘‘om turmush tarzini olib borishga, sport bilan shug‘ullanishga, to‘g‘ri ovqatlanishga harakat qilaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это замечательно! Физическая активность действительно важна.",
          uz: "Bu juda zo’r! Haqiqatdan ham, jismoniy faollik juda muhim.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Да, спорт помогает поддерживать тело в форме и улучшает настроение.",
          uz: "Ha, sport qaddi qomatinni churoyli saqlashga yordam beradi va kayfiyatingni ko’taradi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "А как насчет питания?",
          uz: "Ovqat-chi?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Я стараюсь употреблять больше фруктов, овощей и здоровых белков.",
          uz: "Men ko'proq meva, sabzavot va foydali oqsillarni iste'mol qilishga harakat qilaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это правильный подход. Здоровое питание играет ключевую роль в общем состоянии организма.",
          uz: "Bu to'g'ri yondashuv. Sog'lom ovqatlanish tananing umumiy holatida muhim rol o'ynaydi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Согласен. Кроме того, важно не забывать о достаточном количестве воды.",
          uz: "Gapinga qo’shilaman. Bundan tashqari, yetarli miqdordagi suv  haqida unutmaslik zarur.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Да, это очень важно для здоровья кожи, волос и всего организма.",
          uz: "Ha, bu narsa terining, sochning va butun tananing salomatligi uchun juda muhimdir.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Какие еще привычки помогают тебе поддерживать здоровье?",
          uz: "Yana qanaqa odatlaring salomatlikni saqlashga yordam beradi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Я стараюсь ходить на свежий воздух и следить за сном.",
          uz: "Toza havoda sayr qilishga, uyquni nazorat qilishga harakat qilaman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Отличные привычки! Сон и отдых играют большую роль в поддержании иммунитета.",
          uz: "Zo’r odatlar! Immunitetni saqlashda uyqu va dam olish katta rol o'ynaydi.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Пробовал ли ты когда-нибудь закаляться?",
          uz: "Qachon bo’lsa ham o'zingni chiniqtirishga harakat qilganmisan?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Нет, но слышал, что это тоже очень полезно.",
          uz: "Yo'q, lekin bu ham juda foydali deb eshitganman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Спасибо за разговор! Твой подход к здоровому образу жизни очень вдохновляет.",
          uz: "Suhbating uchun rahmat! Sening sog'lom turmush tarziga yondashuving juda ilhomlantiradi.",
        },
      ],
    },

    {
      id: 30,
      theme: "Shifokorga tashrif” mavzusi.",
      theme_ru: "Визит к врачу»",
      dialog: [
        {
          gender: "male",
          person: "1",
          ru: "Здравствуйте, какие у вас жалобы?",
          uz: "Salom, qanday shikoyatlaringiz bor?",
        },
        {
          gender: "male",
          person: "2",
          ru: "У меня болит горло и немного повышена температура.",
          uz: "Tomog'im og'riyapti, haroratim biroz ko'tarilgan.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Сколько дней вас беспокоят эти симптомы?",
          uz: "Bu alomatlar sizni necha kundan beri bezovta qilayapti?",
        },
        {
          gender: "male",
          person: "2",
          ru: "Примерно три дня.",
          uz: "Taxminan uch kun.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Пейте много жидкости, возможно, это просто простуда.",
          uz: "Ko'p suyuqlik iching, bu shunchaki shamollash bo'lishi mumkin.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Но у меня еще кашель и слабость.",
          uz: "Lekin menda yo'tal va zaiflik ham bor.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Хорошо, я назначу вам анализы.",
          uz: "Mayli, men sizga tahlilarni tayinlayman.",
        },
        {
          gender: "male",
          person: "2",
          ru: "А что это позволит выяснить?",
          uz: "Bu nimani aniqlashga imkon beradi?",
        },
        {
          gender: "male",
          person: "1",
          ru: "Это поможет определить возможные причины вашего состояния.",
          uz: "Bu sizning hozirgi ahvolingizning sababini aniqlashga yordam beradi.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошо, я сделаю анализы.",
          uz: "Yaxshi, men tahlillarni topshiraman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Кроме того, возьмите этот рецепт на лекарства от кашля.",
          uz: "Shuningdek, yo'talga qarshi dori-darmonlar yozilgan mana shu reseptni oling.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Спасибо, обязательно куплю лекарства.",
          uz: "Rahmat, men albatta dorilarni sotib olaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "И не забудьте позвонить мне после результатов анализов.",
          uz: "Tahlillar natijalaridan keyin menga qo'ng'iroq qilishni unutmang.",
        },
        {
          gender: "male",
          person: "2",
          ru: "Хорошо, обязательно свяжусь с вами.",
          uz: "Mayli, men siz bilan albatta bog'lanaman.",
        },
        {
          gender: "male",
          person: "1",
          ru: "Надеюсь, что скоро почувствуете себя лучше. Всего доброго!",
          uz: "Umid qilamanki, tez orada o'zingizni yaxshi his qilasiz. Yaxshi boring!",
        },
      ],
    },
  ];

  function eventDialog(item) {
    let d = dialogs.filter((dialog) => dialog.id == item)[0];
    return d;
  }

  return { dialogs, eventDialog };
});
